;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Input.Native.Jump",NewTagName="Input.Ability.Jump")
+GameplayTagRedirects=(OldTagName="Ability.ConsumeItem",NewTagName="Ability.UseItem")
+GameplayTagRedirects=(OldTagName="Input.Ability.ConsumeItem",NewTagName="Input.Ability.UseItem")
+GameplayTagRedirects=(OldTagName="EnemyAbility.HitDownward",NewTagName="EnemyAbility.ChopDown")
+GameplayTagList=(Tag="Ability.Dodge",DevComment="")
+GameplayTagList=(Tag="Ability.Focus",DevComment="")
+GameplayTagList=(Tag="Ability.Hit",DevComment="")
+GameplayTagList=(Tag="Ability.Jump",DevComment="")
+GameplayTagList=(Tag="Ability.Knockback",DevComment="")
+GameplayTagList=(Tag="Ability.MeleeAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Parry",DevComment="")
+GameplayTagList=(Tag="Ability.ParrySuccess",DevComment="")
+GameplayTagList=(Tag="Ability.Pickup",DevComment="")
+GameplayTagList=(Tag="Ability.UseItem",DevComment="")
+GameplayTagList=(Tag="Character.Hero",DevComment="")
+GameplayTagList=(Tag="Character.Slime",DevComment="")
+GameplayTagList=(Tag="EnemyAbility",DevComment="")
+GameplayTagList=(Tag="EnemyAbility.ChopDown",DevComment="")
+GameplayTagList=(Tag="EnemyAbility.Neutralize",DevComment="")
+GameplayTagList=(Tag="EnemyAbility.Retreat",DevComment="")
+GameplayTagList=(Tag="EnemyAbility.RunAndVerticalSlash",DevComment="")
+GameplayTagList=(Tag="Event.Enemy",DevComment="")
+GameplayTagList=(Tag="Event.Enemy.Montage",DevComment="")
+GameplayTagList=(Tag="Event.Enemy.Montage.ChopDown",DevComment="")
+GameplayTagList=(Tag="Event.Enemy.Montage.RunAndVerticalSlash",DevComment="")
+GameplayTagList=(Tag="Event.Enemy.Neutralize",DevComment="")
+GameplayTagList=(Tag="Event.Hero",DevComment="")
+GameplayTagList=(Tag="Event.Hero.Knockback",DevComment="")
+GameplayTagList=(Tag="Event.Hero.Montage",DevComment="")
+GameplayTagList=(Tag="Event.Hero.Montage.MeleeAttack",DevComment="")
+GameplayTagList=(Tag="Event.Hero.ParrySuccess",DevComment="")
+GameplayTagList=(Tag="Input.Ability",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Dodge",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Focus",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Jump",DevComment="")
+GameplayTagList=(Tag="Input.Ability.MeleeAttack",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Parry",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Pickup",DevComment="")
+GameplayTagList=(Tag="Input.Ability.UseItem",DevComment="")
+GameplayTagList=(Tag="Input.Native.Look",DevComment="")
+GameplayTagList=(Tag="Input.Native.Move",DevComment="")
+GameplayTagList=(Tag="Item.Potion",DevComment="")
+GameplayTagList=(Tag="Item.Sword",DevComment="")
+GameplayTagList=(Tag="Message.EquipItem",DevComment="")
+GameplayTagList=(Tag="Message.EquipWeapon",DevComment="")
+GameplayTagList=(Tag="Message.ItemOverlap",DevComment="")
+GameplayTagList=(Tag="Message.LockOn",DevComment="")
+GameplayTagList=(Tag="Message.PickupItem",DevComment="")
+GameplayTagList=(Tag="Message.UseItem",DevComment="")
+GameplayTagList=(Tag="State.HasWeapon",DevComment="")
+GameplayTagList=(Tag="State.Invincible",DevComment="")
+GameplayTagList=(Tag="State.Knockback",DevComment="")
+GameplayTagList=(Tag="State.MoveBlocked",DevComment="")
+GameplayTagList=(Tag="State.Neutralize",DevComment="")
+GameplayTagList=(Tag="State.Parrying",DevComment="")
+GameplayTagList=(Tag="State.RegenStamina",DevComment="")
+GameplayTagList=(Tag="State.RegenStaminaBlocked",DevComment="")

